language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/balloons_test

node_js:  
  - "12"

before_script:
  - psql -c 'create database  balloons_test;' -U postgres
  - psql -U postgres -d balloons_test -a -f the_balloon_test.sql

services:
  - postgresql